project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /**/en/*.md
    translation: /**/%two_letters_code%/%original_file_name%
    ignore:
      - /coalition-publica
      - /crossref-ojs2-manual
      - /learning-ojs-2
      - /learning-ojs/3.1
      - /learning-ojs/3.2
      - /ojs-2-technical-reference
      - /using-paypal-for-ojs-and-ocs