# This line should *not* be indented
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
# These lines should *not* be indented
media_folder: "assets" # Media files will be stored in the repo under static/images/uploads
public_folder: "assets" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "admin-guide" # Used in routes, e.g., /admin/collections/blog
    label: "Admin Guide" # Used in the UI
    folder: "admin-guide" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Body", name: "body", widget: "markdown"}