name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Thank you for helping out with documentation! To find more details about contributing, check out our contributing guide: https://docs.pkp.sfu.ca/contributing/'' first pr'
